version: "3.1"
services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FILE_UID: ${FILE_UID}
        FILE_GID: ${FILE_GID}
    ports:
      - "${WWW_PORT}:80"
    volumes:
      - ./docker/apache2/conf_local:/etc/apache2/sites-available
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./application:/var/www/html/
    links:
      - db
    networks:
      - default
  db:
    image: mysql:8.0.0
    ports:
      - "${MYSQL_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker/dump:/docker-entrypoint-initdb.d
      #   - ./docker/conf:/etc/mysql/conf.d
      - ./docker/mysql_conf/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql:/var/lib/mysql:rw,delegated
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
